## Добавим HPA для экономии ресурсов
apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: mindbox-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment ## Стейтлесс приложение
    name: mindbox ## Смотрим на наш апп
  minReplicas: 2 ## Укажу 2, т.к. это что-то среднее между отказоустойвостью и энономией ресурсов (с учетом распредления по зонам и разным нодам). 1 - ну всякое может случится с нодой/зоной ночью, получим на какое-то время 500-ки (сервис стартует быстро, но все равно сомнительная экономия, с учетом того, что потребление не высокое).
  maxReplicas: 4 ## Если по результатам нагрузочного тестирования 4 реплики справляются, значит смысла в большем кол-ве нет (хотя можно поспорить "что значит 4 пода"? - лучше бы конечно знать пиковую утилазацию по цпу)
  metrics:
    - type: Resource
      resource:
        name: cpu ## В тз сказано что память у нас стабильна, поэтому делаем только на основе процессора (можно конечно и на основе метрик прикрутить, но работаем с чем что есть)
        target:
          type: Utilization
          averageUtilization: 80 ## Поставлю 80%, но тут опять же, неплохохо бы видеть график "скачков", если они будут плавные (допустим между 70-90%) и нагрузка будет расти равномерно, то это хорошая метрика средней утилизации
